In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:

### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9569, 1642, 7297, 1838], [9569, 1642, 7297, 8610], [9569, 1622, 7297, 7054], [1166, 7865, 8614, 8159, 2159], [1166, 7865, 8614, 8159, 4081], [5139, 9569, 6186, 7297, 3309], [1386, 4753, 9742, 8159]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9569 1642 7297 1838]
 [   0    0    0    0 9569 1642 7297 8610]
 [   0    0    0    0 9569 1622 7297 7054]
 [   0    0    0 1166 7865 8614 8159 2159]
 [   0    0    0 1166 7865 8614 8159 4081]
 [   0    0    0 5139 9569 6186 7297 3309]
 [   0    0    0    0 1386 4753 9742 8159]]


In [9]:

dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307
    0.02179584  0.01951781  0.00525593  0.02556017  0.04008006]
  [ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307
    0.02179584  0.01951781  0.00525593  0.02556017  0.04008006]
  [ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307
    0.02179584  0.01951781  0.00525593  0.02556017  0.04008006]
  [ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307
    0.02179584  0.01951781  0.00525593  0.02556017  0.04008006]
  [ 0.03760106  0.00891749 -0.00104166  0.03428258 -0.03509588
    0.00059436  0.02009728  0.00894618 -0.00821992 -0.0347757 ]
  [-0.04132145 -0.01498488  0.02189754 -0.04274317  0.01517067
    0.02475127  0.02941776  0.02854809 -0.04250219  0.04116795]
  [ 0.04349257  0.01610691 -0.04354173  0.01195998 -0.02991968
   -0.00610114 -0.04093213 -0.00559865 -0.02752488  0.00788251]
  [ 0.02431524 -0.03600364  0.00563516  0.03002795 -0.02801958
   -0.03546083 -0.03133891  0.03053255  0.03611816 -

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9569, 1642, 7297, 1838])

In [14]:
print(model.predict(embedded_docs)[0])

[[ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307   0.02179584
   0.01951781  0.00525593  0.02556017  0.04008006]
 [ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307   0.02179584
   0.01951781  0.00525593  0.02556017  0.04008006]
 [ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307   0.02179584
   0.01951781  0.00525593  0.02556017  0.04008006]
 [ 0.0421862   0.04991753 -0.02772259 -0.02172507  0.0377307   0.02179584
   0.01951781  0.00525593  0.02556017  0.04008006]
 [ 0.03760106  0.00891749 -0.00104166  0.03428258 -0.03509588  0.00059436
   0.02009728  0.00894618 -0.00821992 -0.0347757 ]
 [-0.04132145 -0.01498488  0.02189754 -0.04274317  0.01517067  0.02475127
   0.02941776  0.02854809 -0.04250219  0.04116795]
 [ 0.04349257  0.01610691 -0.04354173  0.01195998 -0.02991968 -0.00610114
  -0.04093213 -0.00559865 -0.02752488  0.00788251]
 [ 0.02431524 -0.03600364  0.00563516  0.03002795 -0.02801958 -0.03546083
  -0.03133891  0.03053255  0.03611816 -0.0046908 ]]

***Pretrained***

In [ ]:
import numpy as np
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

In [ ]:

import gensim.downloader as api
word2vec_model = api.load('word2vec-google-news-300')

In [ ]:
word2vec_model["beautiful"]

In [ ]:
word2vec_model.most_similar("girl")

In [ ]:
word2vec_model.most_similar(positive=['boy', 'queen'], negative=['girl'], topn=1)

In [ ]:
vocab = ["boy", "girl", "man", "woman", "king", "queen", "banana", "apple", "mango", "fruit", "coconut", "orange"]

def tsne_plot(model):
    labels = []
    wordvecs = []

    for word in vocab:
        wordvecs.append(model[word])
        labels.append(word)
    
    tsne_model = TSNE(perplexity=3, n_components=2, init='pca', random_state=42)
    coordinates = tsne_model.fit_transform(wordvecs)

    x = []
    y = []
    for value in coordinates:
        x.append(value[0])
        y.append(value[1])
        
    plt.figure(figsize=(8,8)) 
    for i in range(len(x)):
        plt.scatter(x[i],y[i])
        plt.annotate(labels[i],
                     xy=(x[i], y[i]),
                     xytext=(2, 2),
                     textcoords='offset points',
                     ha='right',
                     va='bottom')
    plt.show()

tsne_plot(word2vec_model)